CREATE TABLE autores (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE cursos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    categoria VARCHAR(50) NOT NULL
);

CREATE TABLE topicos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    mensagem TEXT NOT NULL,
    data_criacao DATETIME NULL DEFAULT CURRENT_TIMESTAMP,  
    status VARCHAR(255) NOT NULL,
    autor BIGINT,  
    curso INT,
    FOREIGN KEY (autor) REFERENCES autores(id) ON DELETE CASCADE,
    FOREIGN KEY (curso) REFERENCES cursos(id) ON DELETE SET NULL
);

CREATE TABLE respostas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    mensagem TEXT NULL,
    topico INT,
    data_criacao DATETIME DEFAULT NULL CURRENT_TIMESTAMP,
    autor BIGINT,  
    solucao VARCHAR(255) NOT NULL,
    
    FOREIGN KEY (topico) REFERENCES topicos(id) ON DELETE CASCADE,
    FOREIGN KEY (autor) REFERENCES autores(id) ON DELETE CASCADE
);